swagger: '2.0'
info:
  title: LiquidIoT DM APIs
  version: "0.2"
produces:
  - application/json
consumes:
  - application/json
paths:
  /apis:
    get:
      summary: Array of names and short descriptions of classes that have an API description
      responses:
        '200':
          description: Array of class names and descriptions
          schema:
            type: array
            items:
              type: object
              properties:
                  name:
                      type: string
                  description:
                      type: string
  /apis/{className}:
    get:
      summary: API description of the class
      parameters:
        - name: className
          description: Name of the class
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Swagger fragment
          schema:
            $ref: '#/definitions/swaggerFragment'
        '404':
            description: class not found
            schema:
                $ref: "#/definitions/error404"
        '500':
            description: "server error"
            schema:
                $ref: "#/definitions/error500"
    put:
      summary: Create or replace the API description
      parameters:
        - name: className
          description: Name of the class
          in: path
          required: true
          type: string
        - name: api
          description: Name of the class
          in: body
          required: true
          schema:
            $ref: '#/definitions/swaggerFragment'
      responses:
        '200':
          description: Swagger fragment
          schema:
            $ref: '#/definitions/swaggerFragment'
        '500':
            description: "server error"
            schema:
                $ref: "#/definitions/error500"
    delete:
      summary: Delete the API description
      parameters:
        - name: className
          description: Name of the class
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Swagger fragment
          schema:
            $ref: '#/definitions/swaggerFragment'
        '404':
            description: class not found
            schema:
                $ref: "#/definitions/error404"
        '500':
            description: "server error"
            schema:
                $ref: "#/definitions/error500"
  /devices/{deviceId}/apps/{appId}/api:
    get:
      summary: Swagger API description of the application
      description: The API description combines the Swagger fragments of all the classes of the application. It also contains the host and basePath of the currently running application.
      parameters:
        - name: deviceId
          description: Device ID
          in: path
          required: true
          type: string
        - name: appId
          description: Application ID
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Full Swagger description
          schema:
            $ref: '#/definitions/swaggerDescription'
        '404':
            description: device, app or classes the app refers to  not found
            schema:
                $ref: "#/definitions/error404"
        '500':
            description: "server error"
            schema:
                $ref: "#/definitions/error500"

definitions:
  swaggerFragment:
    type: object
    description: Swagger API description excluding host, basePath, and schemes
  swaggerDescription:
    type: object
    description: Swagger API description
  error404:
      description: error message
      type: object
      properties:
          message:
              type: string
  error500:
      description: error message
      type: object